version: '2'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8

  mongodb:
    image: mongo:4.0.17-xenial
    restart: always
    volumes:
      - ../slides_checker_mongo_data:/data/db
